<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.tlc.live</groupId>
        <artifactId>tlc-live-substrate</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>substrate-push</artifactId>
    <name>substrate-push</name>
    <description>微服务五：高密下行推送集群（Redis Pub/Sub 解耦 + 海量 WebSocket 广播）</description>

    <dependencies>
        <dependency>
            <groupId>com.tlc.live</groupId>
            <artifactId>substrate-common</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-websocket</artifactId>
        </dependency>
        <!-- 订阅网关/秒杀服务发布的结果事件，实现内外网数据解耦 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
