<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.tlc.live</groupId>
        <artifactId>tlc-live-substrate</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>substrate-toggle</artifactId>
    <name>substrate-toggle</name>
    <description>微服务七：动态降级与特征开关（内存热开关 + 一键保命切换）</description>

    <dependencies>
        <dependency>
            <groupId>com.tlc.live</groupId>
            <artifactId>substrate-common</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
